app_vehicles_post:
    path: /vehicles
    controller: App\Controller\VehiclesController::postVehicle
    methods: POST
app_vehicles_get:
    path: /vehicles/{year}/{manufacturer}/{model}
    controller: App\Controller\VehiclesController::findVehicle
    methods: GET
