app_vehicles_get_all:
    path: /vehicles
    controller: App\Controller\VehiclesController::postVehicle
    methods: POST
app_vehicles_get_one:
    path: /vehicles/{year}/{mark}/{model}
    controller: App\Controller\VehiclesController::findVehicle
    methods: GET
